title : Mayank Jain
logo : /assets/img/mayankjain_profilepic.png
description : Digital Analytics and Personalization Specialist with a strong background in Adobe Target, Adobe Analytics, and CRO. Skilled in driving revenue growth and optimizing KPIs through A/B testing, dynamic personalization, and data-driven strategies for diverse clients. Proficient in automation and leveraging cloud platforms to deliver impactful insights.
#show_downloads : true
theme : jekyll-theme-minimal
