title : Mayank Jain
logo : /assets/img/mayankjain_profilepic.png
description : Digital Analytics and Personalization Specialist driving revenue growth and optimized KPIs through A/B testing, dynamic personalization, and cloud-powered insights.
#show_downloads : true
theme : jekyll-theme-minimal
