title : Mayank Jain
logo : /assets/img/mayankjain_profilepic.png
description : Passionate about Data, Tech and Personal Finance
show_downloads : true
theme : jekyll-theme-minimal
resume_url : mayankjain/assets/resume/MayankJain_Resume.pdf
